version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: fp-ts
    versions:
    - 2.10.0
    - 2.10.3
    - 2.9.3
    - 2.9.4
    - 2.9.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/pg"
    versions:
    - 7.14.10
    - 7.14.9
  - dependency-name: "@slack/bolt"
    versions:
    - 3.1.1
    - 3.2.0
  - dependency-name: "@slack/web-api"
    versions:
    - 6.0.0
  - dependency-name: "@types/cors"
    versions:
    - 2.8.9
  - dependency-name: pg
    versions:
    - 8.5.1
